 
//----------------------
// <auto-generated>
//     AWSOA.Core.CodeGeneration
// </auto-generated>
//----------------------
using System;
using System.Collections;
using System.Collections.Generic;
using AWSOA.Core.Contracts.DataTransferObject;
using AWSOA.Core.Contracts.Extensions;

namespace AW.Clarity.PatternViewer.Contracts.DataTransferObject
{
    //[Serializable]
    [System.CodeDom.Compiler.GeneratedCode("AWSOA.Commercial.CodeGeneration", "13.0.0.0")]
    public partial class LogoDto 
    {
        #region Factory methods
        /// <summary>
        /// Factory for a LogoDto object
        /// </summary>
        /// <returns>a new instance of the LogoDto object</returns>
        public static LogoDto CreateInstance()
        {
            var dto = new LogoDto();
            dto.Guid = new GuidDto();
            dto.Width = new DecimalDto();
            dto.Height = new DecimalDto();
            dto.CenterX = new DecimalDto();
            dto.CenterY = new DecimalDto();
            return dto;
        }

        /// <summary>
        /// Factory for a LogoDto object
        /// </summary>
        /// <param name="x">Action on the object for initialization</param>
        /// <returns>a new instance of the LogoDto object</returns>
        public static LogoDto CreateInstance(Action<LogoDto> x)
        {
            var dto = CreateInstance();

            x.Invoke(dto);

            return dto;
        }

        #endregion
        
        #region override ToString()
        public override string ToString()
        {
          //var result = "Logo: " + string.Join("; ", 
          var result = string.Join(", ",
                            string.Format("Guid='{0}'", this.Guid),                        
                            string.Format("Format='{0}'", this.Format),
                            string.Format("Width='{0}'", this.Width),                        
                            string.Format("Height='{0}'", this.Height),                        
                            string.Format("CenterX='{0}'", this.CenterX),                        
                            string.Format("CenterY='{0}'", this.CenterY),                        
                            ""
                        );
          return result;
        }

        #region CompositeIdToString()
        //prevent circular ToString()
        internal string CompositeIdToString()
        {
            string result = "...";
            return result;
        }
        #endregion
        #endregion
    }
}
 
