 
//----------------------
// <auto-generated>
//     AWSOA.Core.CodeGeneration
// </auto-generated>
//----------------------
using System;
using System.Collections;
using System.Collections.Generic;
using AWSOA.Core.Contracts.DataTransferObject;
using AWSOA.Core.Contracts.Extensions;

namespace AW.Clarity.PatternViewer.Contracts.DataTransferObject
{
    //[Serializable]
    [System.CodeDom.Compiler.GeneratedCode("AWSOA.Commercial.CodeGeneration", "13.0.0.0")]
    public partial class LogoPositionDto 
    {
        #region Factory methods
        /// <summary>
        /// Factory for a LogoPositionDto object
        /// </summary>
        /// <returns>a new instance of the LogoPositionDto object</returns>
        public static LogoPositionDto CreateInstance()
        {
            var dto = new LogoPositionDto();
            dto.Logo = new GuidDto();
            dto.Bottom = new DecimalDto();
            dto.Left = new DecimalDto();
            dto.MeasureType = AWMeasureTypeDto.CornerEdgeAWMeasureTypeDto;
            return dto;
        }

        /// <summary>
        /// Factory for a LogoPositionDto object
        /// </summary>
        /// <param name="x">Action on the object for initialization</param>
        /// <returns>a new instance of the LogoPositionDto object</returns>
        public static LogoPositionDto CreateInstance(Action<LogoPositionDto> x)
        {
            var dto = CreateInstance();

            x.Invoke(dto);

            return dto;
        }

        #endregion
        
        #region override ToString()
        public override string ToString()
        {
          //var result = "LogoPosition: " + string.Join("; ", 
          var result = string.Join(", ",
                            string.Format("Logo='{0}'", this.Logo),                        
                            string.Format("Bottom='{0}'", this.Bottom),                        
                            string.Format("Left='{0}'", this.Left),                        
                            string.Format("RotationCounterclockwise='{0}'", this.RotationCounterclockwise),                        
                            string.Format("SurfaceLevel='{0}'", this.SurfaceLevel),                        
                            string.Format("SegmentNo='{0}'", this.SegmentNo),                        
                            string.Format("Endpoint='{0}'", this.Endpoint),
                            string.Format("MeasureType='{0}'", this.MeasureType),
                            ""
                        );
          return result;
        }

        #region CompositeIdToString()
        //prevent circular ToString()
        internal string CompositeIdToString()
        {
            string result = "...";
            return result;
        }
        #endregion
        #endregion
    }
}
 
