 
//----------------------
// <auto-generated>
//     AWSOA.Core.CodeGeneration
// </auto-generated>
//----------------------
#pragma once

module AW{
    module Clarity{
		module PatternViewer{
			module Contracts {
				module DataTransferObject{
					// Create the enum for the DTO
					enum PatternDirectionDto
					{
						UndefinedPatternDirectionDto  = 0,
						NextPatternDirectionDto = 1,
						PreviousPatternDirection = 2,
					};
				};
			};
		};
	};
};
